In [1]:
import numpy as np
import math

In [2]:
#Arrays are displayed as lists or lists of lists ,they can also be created through lists as well
#we pass in a list as an argument in numpy array.

In [3]:
arr=np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [6]:
b=np.array([[1,2,3],[4,5,6]])

In [7]:
b[0]

array([1, 2, 3])

In [8]:
b[1]

array([4, 5, 6])

In [9]:
b[0][1]

2

In [12]:
b[1][2]

6

In [14]:
# We can print out the length of each dimension by calling the shape attribute, which returns a tuple
b.shape

(2, 3)

In [17]:
arr.shape

(3,)

In [15]:
# We can also check the type of items in the array
b.dtype

dtype('int32')

In [16]:
arr.dtype

dtype('int32')

In [18]:
# Besides integers, floats are also accepted in numpy arrays
a=np.array([1,2,3.3,1.3])

In [19]:
a.dtype

dtype('float64')

In [20]:
a

array([1. , 2. , 3.3, 1.3])

In [21]:
# Note that numpy automatically converts integers, like 5, up to floats, since there is no loss of prescision.
# Numpy will try and give you the best data type format possible to keep your data types homogeneous, which
# means all the same, in the array

In [23]:
# Numpy offers several functions to create arrays with initial placeholders, such as zero's or one's.
# Lets create two arrays, both the same shape but with different filler values
zero=np.zeros((2,2))

In [24]:
zero

array([[0., 0.],
       [0., 0.]])

In [25]:
one=np.ones((3,4))

In [27]:
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
one.dtype

dtype('float64')

In [33]:
# We can also generate an array with random numbers
rnarr=np.random.rand(3,3)

In [34]:
rnarr

array([[0.55400601, 0.94748424, 0.38705597],
       [0.00811662, 0.75790709, 0.52448874],
       [0.41587494, 0.29121829, 0.55118853]])

In [40]:
print(rnarr)

[[0.55400601 0.94748424 0.38705597]
 [0.00811662 0.75790709 0.52448874]
 [0.41587494 0.29121829 0.55118853]]


In [39]:
# We can also create a sequence of numbers in an array with the arrange() function.
#arrange(starting bound,ending bound,difference between
# each consecutive numbers)

In [44]:
#array of every odd number from one (inclusive) to 10 (exclusive)
arr=np.arange(1,11,2)

In [45]:
arr

array([1, 3, 5, 7, 9])

In [46]:
# if we want to generate a sequence of floats, we can use the linspace() function. In this function the third
# argument isn't the difference between two numbers, but the total number of items you want to generate

In [50]:
arr=np.linspace(1,11,10)

In [51]:
arr

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

# Array Operations

In [52]:
# We can do many things on arrays, such as mathematical manipulation (addition, subtraction, square,
# exponents) as well as use boolean arrays, which are binary values. We can also do matrix manipulation such
# as product, transpose, inverse, and so forth.

In [68]:
a=np.array([1,2,3])
b=np.array([1,2,3])

#addition
c=a+b
print(c)

#subtraction
s=a-b
print(s)

[2 4 6]
[0 0 0]


In [62]:
# With arithmetic manipulation, we can convert current data to the way we want it to be.
fah=np.array([-5,0,-10,5])
celsius=(fah-31)*(5/9)

In [63]:
celsius

array([-20.        , -17.22222222, -22.77777778, -14.44444444])

In [65]:
# Another useful and important manipulation is the boolean array.
celsius>-20

array([False,  True, False,  True])

In [66]:
celsius%2==0

array([ True, False, False, False])

In [70]:
# Besides elementwise manipulation, it is important to know that numpy supports matrix manipulation.


A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])

#if we want to do elementwise product, we use the "*" sign
print(A*B)

print()

# if we want to do matrix product, we use the "@" sign or use the dot function
print(A@B)

[[ 1  4]
 [ 9 16]]

[[ 7 10]
 [15 22]]


In [71]:
# numpy is the underpinning of scientific computing libraries in python, and that it is capable of doing both
# element-wise operations (the asterix) as well as matrix-level operations (the @ sign).

# A few more linear algebra concepts are worth layering in here. You might recall that the product of two
# matrices is only plausible when the inner dimensions of the two matrices are the same. The dimensions refer
# to the number of elements both horizontally and vertically in the rendered matricies you've seen here. We
# can use numpy to quickly see the shape of a matrix:

In [76]:
# When manipulating arrays of different types, the type of the resulting array will correspond to 
# the more general of the two types. This is called upcasting.

a=np.array([1,2,3])
b=np.array([17.23,12,6])
c=a+b
print(a.dtype,b.dtype,c.dtype)       # Notice how the items in the resulting array have been upcast into floating point numbers

int32 float64 float64


In [81]:
# Numpy arrays have many interesting aggregation functions on them, such as  sum(), max(), min(), and mean()
print(b.sum())
print(b.max())
print(b.min())
print(b.mean())

35.230000000000004
17.23
6.0
11.743333333333334


In [84]:
# let's create an array with 15 elements, ranging from 1 to 10, 
# with a dimension of 3X5
arr=np.arange(1,11,1).reshape(5,2)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


# Indexing ,Slicing, Iterating

In [86]:
arr=np.array([[1,2,3],[4,5,6]])

In [87]:
arr[0]

array([1, 2, 3])

In [89]:
# if we want to select one certain element, we can do so by entering the index, which is comprised of two
# integers the first being the row, and the second the column
arr[0,1]

2

In [91]:
# if we want to get multiple elements 
# and put them into a one-dimensional array
# we can enter the indices directly into an array function
a=np.array([arr[0,0],arr[1,0],arr[1,1]])

In [99]:
a

array([1, 4, 5])

In [97]:
# we can also do that by using another form of array indexing, which essentiall "zips" the first list and the
# second list up
b=(arr[[0,1,1],[0,0,1]])

In [98]:
b

array([1, 4, 5])

# Boolean Indexing 

In [103]:
# Boolean indexing allows us to select arbitrary elements based on conditions. For example, in the matrix we
# just talked about we want to find elements that are greater than 5 so we set up a conditon a >5 
print(arr >2)
# This returns a boolean array showing that if the value at the corresponding index is greater than 5

[[False False  True]
 [ True  True  True]]


In [102]:
# We can then place this array of booleans like a mask over the original array to return a one-dimensional 
# array relating to the true values.
print(arr[arr>4])

[5 6]


# slicing

In [104]:
# Slicing is a way to create a sub-array based on the original array. For one-dimensional arrays, slicing 
# works in similar ways to a list. 
a=np.array([1,2,3,4,5])
a[:2]

array([1, 2])

In [105]:
a[:4]

array([1, 2, 3, 4])

In [107]:
a[1:4]

array([2, 3, 4])

In [110]:
# For multi-dimensional arrays, it works similarly, lets see an example
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a.shape

(3, 4)

In [111]:
# First, if we put one argument in the array, for example a[:2] then we would get all the elements from the 
# first (0th) and second row (1th)
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [113]:
# If we add another argument to the array, for example a[:2, 1:3], we get the first two rows but then the
# second and third column values only
a[:3, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [114]:
# So, in multidimensional arrays, the first argument is for selecting rows, and the second argument is for 
# selecting columns

In [115]:
# It is important to realize that a slice of an array is a view into the same data. This is called passing by
# reference. So modifying the sub array will consequently modify the original array

# Here I'll change the element at position [0, 0], which is 2, to 50, then we can see that the value in the
# original array is changed to 50 as well

sub_array = a[:2, 1:3]
print("sub array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 50
print("sub array index [0,0] value after change:", sub_array[0,0])
print("original array index [0,1] value after change:", a[0,1])

sub array index [0,0] value before change: 2
sub array index [0,0] value after change: 50
original array index [0,1] value after change: 50
